### ISSUE TITLE
[Bug report]: Dialog does not move to associated tab when a validation error occurs

### ISSUE THREAD

**Issue by liamrhomer** [serenity-is/Serenity#7002] opened 2023-11-03 11:51 UTC
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

When there is an empty or incorrect field in a tabbed dialog, it does not switch to the tab with the field and stays in place on the current tab.

This issue occurs both on the online StartSharp Demo and also on my local machine using the latest packages.

### What did you expect to happen?

In older versions of Serenity, this would automatically move you to the tab where the field was incorrect.

### How to reproduce?

When looking at the Startsharp demo at: https://demo.serenity.is/ and going to the following page: https://demo.serenity.is/BasicSamples/OtherFormInTab.

If you delete the order date in one of the entries, move to the second tab "Shipping" and hit save, it indicates that "This field is required." and gives a validation error message but it does not switch tabs back to "General".

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.9.5

### On which device do you see the problem?

Laptop

### On which operating system do you see the problem?

Windows

### On which browsers do you see the problem?

Microsoft Edge

### On what version of the browsers do you see the problem?

119.0.2151.44

**Comment by VictorTomaili** [comment] 2023-11-03 12:22
This is not a bug; we didn't have such a feature. We'll add to our backlog.

**Comment by volkanceylan** [comment] 2023-11-03 15:10
Seems like we had a workaround but it no longer works with Bootstrap 5 as it does not use jquery. This will be re-fixed in 6.9.6

**Closed** 2023-11-11 13:30 UTC
Labels: waiting-for-check
